DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'kairn_app') THEN
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM kairn_app;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM kairn_app;
    REVOKE ALL ON ALL TABLES IN SCHEMA public FROM kairn_app;
    REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM kairn_app;
    REVOKE USAGE ON SCHEMA public FROM kairn_app;
  END IF;
END $$;
