// Contenu éditorial du site vitrine, en anglais. Même structure et mêmes
// données de démonstration que la version française (fr.ts), adaptées aux
// conventions anglophones (€48,214, 96.4%, GiB).

import type { Content } from "./types";

export const en: Content = {
  locale: "en",
  htmlLang: "en",
  numberLocale: "en-GB",
  meta: {
    title: "Kairn — Cost observability for sovereign clouds, OpenStack and Kubernetes",
    description:
      "Kairn connects costs, usage and deployments across OVHcloud, Scaleway, OUTSCALE, OpenStack and Kubernetes: what you spend, whether it's well used, and why it changed. Sovereign FinOps, hosted in the EU or self-hosted.",
    keywords: [
      "FinOps",
      "sovereign FinOps",
      "cloud costs",
      "cost observability",
      "OVHcloud",
      "Scaleway",
      "OUTSCALE",
      "OpenStack",
      "Kubernetes",
      "showback",
      "chargeback",
      "rightsizing",
      "sovereign cloud",
      "Kubernetes cost allocation",
    ],
    ogLocale: "en_GB",
    ogAlt: "Kairn — the real cost of your cloud, finally explained",
    ogTitle: "The real cost of your cloud, finally explained.",
    ogTagline: ["Sovereign FinOps", "Hosted in the EU or on your premises", "Read-only"],
  },
  ui: {
    skip: "Skip to content",
    home: "Kairn, home",
    mainNav: "Main navigation",
    footerNav: "Footer",
    menu: "Menu",
    nav: [
      { href: "#cascade", label: "How it works" },
      { href: "#produit", label: "Product" },
      { href: "#ia", label: "AI" },
      { href: "#souverainete", label: "Sovereignty" },
      { href: "#tarifs", label: "Pricing" },
      { href: "#faq", label: "FAQ" },
    ],
    docs: "Documentation",
    login: "Sign in",
    demo: "Book a demo",
    demoSubject: "Kairn demo request",
    otherLocale: { href: "/", hrefLang: "fr", label: "FR", aria: "Version française" },
    hero: {
      badge: "Sovereign FinOps · hosted in the EU or on your premises",
      titleA: "The real cost of your cloud, ",
      titleB: "finally explained.",
      text: "From your OVHcloud, Scaleway, OUTSCALE or OpenStack invoice down to the Kubernetes pod: know what you spend, whether it's well used — and why it changed.",
      secondary: "See how it works",
      checks: ["Read-only connectors", "First costs in under an hour", "Full self-hosted edition"],
      scroll: "Scroll down",
    },
    sourcesTitle: "Plugs into what you already run — no new monitoring stack",
    problem: {
      eyebrow: "The problem",
      titleA: "Your invoice tells you how much.",
      titleB: "Never who, or why.",
      text: "Today's FinOps tools are built for AWS, Azure and GCP. On sovereign clouds, OpenStack and Kubernetes, teams end up in a spreadsheet. Kairn turns the same invoice into answers.",
    },
    cascade: {
      eyebrow: "How it works",
      titleA: "From the invoice down to the pod.",
      titleB: "Then on to the team that pays.",
      text: "Kairn links the invoice, cloud projects, VMs, Kubernetes nodes and the pods running on them. Every euro flows down the chain, with its source.",
    },
    product: {
      eyebrow: "Product",
      title: "Three questions. A hard number for every team.",
      text: "Every amount can be traced back to its source: invoice line, versioned price list or metric.",
      bullets: [
        ["Versioned public price lists and real invoices", "Team → service → environment hierarchy", "Chargeback export as CSV or via the API"],
        ["Real usage at the 95th percentile, over a rolling window", "Orphaned resources and environments left on overnight", "kubectl, OpenStack or Terraform command included"],
        ["Seasonal baseline for every cost series", "Deployments, HPA, incidents and inventory cross-checked", "Generated explanation, backed by evidence"],
      ],
    },
    features: { eyebrow: "Everything else", title: "From invoice to action, no spreadsheet required" },
    ai: {
      eyebrow: "AI assistant",
      title: "Ask the question. Get verified numbers.",
      text: "The assistant queries your data through typed tools, with exactly your permissions. Every number in its answer is checked against those tools' results, and its sources are cited.",
      bullets: [
        "Anthropic, Mistral (sovereign option) or a local model — or no AI at all",
        "No calls outside the EU without your organisation's explicit consent",
        "Monthly executive report written for leadership, sent as a PDF",
        "MCP server: your own AI agents query Kairn with your permissions",
      ],
      aria: "Example conversation with the Kairn assistant",
      question: "Why did the Data team's costs go up this month?",
      answer: [
        ["The Data team spent ", { b: "€14,950" }, " in September, ", { b: "€3,290 more" }, " (+28.2%) than in August."],
        [
          "Most of the increase comes from storage: ",
          { b: "+€2,480" },
          " after the ",
          { code: "etl-v2.3" },
          " deployment on the 14th, which created 12 volumes — 9 of them are no longer attached.",
        ],
      ],
      action: ["Suggested action: delete the 9 orphaned volumes (", { b: "−€612/month" }, "). The command is ready in the recommendation."],
      sources: "Sources: costs by team, Argo CD events, volume inventory.",
      caption: "Illustrative example, demo data.",
    },
    personas: { eyebrow: "Who it's for", title: "One source of truth, from engineers to finance" },
    steps: { eyebrow: "Getting started", title: "Up and running in a day, not a quarter" },
    sovereignty: {
      eyebrow: "Sovereignty",
      titleA: "Your cost data stays in Europe. ",
      titleB: "Or with you.",
      text: "Your costs reveal your architecture, your volumes and your customers. Kairn is designed so you stay in control of them.",
    },
    security: { eyebrow: "Security", title: "Built for the requirements of large enterprises and the public sector" },
    integrations: { eyebrow: "Integrations", title: "In your tools and your pipelines" },
    pricing: {
      eyebrow: "Pricing",
      title: "Priced on value, not on resource count",
      text: "Indicative prices, excluding VAT. Each plan's limits are enforced by the platform.",
      highlight: "Most complete",
      contact: "Contact us",
      demo: "Book a demo",
      planSr: "plan",
    },
    faqTitle: "Frequently asked questions",
    cta: {
      titleA: "See your own costs, ",
      titleB: "explained.",
      text: "A 30-minute demo tailored to your context: clouds, Kubernetes, team structure and sovereignty requirements.",
      docs: "Explore the documentation",
    },
    footer: {
      tagline: "Cost observability for sovereign clouds, OpenStack and Kubernetes.",
      product: "Product",
      howItWorks: "How it works",
      features: "Features",
      assistant: "AI assistant",
      pricing: "Pricing",
      resources: "Resources",
      connectors: "Connectors",
      securityLink: "Security",
      contact: "Contact",
      rights: "All rights reserved.",
    },
  },
  mock: {
    aria: "Preview of the Kairn interface with demo data",
    windowTitle: "app.kairn · Acme Retail · Overview",
    sidebar: ["Overview", "Cost explorer", "Cost × usage", "Allocation", "Recommendations", "Anomalies", "Budgets", "AI assistant"],
    kpis: [
      { label: "Spend this month", value: "€48,214", sub: "+6.2%", tone: "warn" },
      { label: "Month-end forecast", value: "€61,900", sub: "budget €64,000", tone: "muted" },
      { label: "Potential savings", value: "€7,420/mo", sub: "18 recommendations", tone: "good" },
      { label: "Allocated costs", value: "96.4%", sub: "target > 95%", tone: "good" },
    ],
    chartTitle: "Daily cost by provider",
    chartRange: "Last 20 days",
    legend: ["OVHcloud", "Kubernetes", "Storage"],
    anomalyTitle: "Anomaly detected",
    anomalyHeadline: "Data team storage: +38% since the 14th",
    anomalyText: ["Coincides with the ", { code: "etl-v2.3" }, " deployment (Argo CD): 12 × 500 GB volumes created, 9 of them unattached."],
    recoLabel: "Recommendation",
    recoText: "Delete 9 orphaned volumes",
    recoSaving: "−€612/mo",
    chipAccepted: "Recommendation accepted",
    chipCorrelated: "Correlated automatically",
    caption: "Interface preview — demo data.",
  },
  visuals: {
    demoNote: "Illustration — demo data.",
    invoiceTitle: "What your invoice says",
    invoiceBadge: "Provider PDF",
    invoiceTotalLabel: "Total excl. VAT",
    invoiceQuestion: "Who consumed that €31,480 of instances? Why +6% this month? The invoice won't tell you.",
    kairnTitle: "What Kairn tells you",
    kairnBadge: "96.4% allocated",
    kairnHighlight: [{ b: "Data team +28%" }, ": 12 volumes created by the ", { code: "etl-v2.3" }, " deployment, 9 of them orphaned."],
    drilldownAria: "How a cost flows from the invoice down to the pod, then to the team",
    allocationAria: "Spend broken down by team",
    allocationTitle: "September spend",
    allocationCoverage: "Coverage 96.4%",
    allocationTotal: "€48,214",
    rightsizing: {
      aria: "Example rightsizing recommendation",
      replicas: "3 replicas",
      badge: "Oversized ×3",
      cpu: "CPU (P95, 30 days)",
      memory: "Memory (P95, 30 days)",
      usedOf: "used of",
      reserved: "reserved",
      memoryUnit: "GiB",
      comment: "# Ready-to-apply command",
      saving: "−€227/month estimated",
      risk: "Low risk",
      measured: "Savings measured after rollout",
    },
    correlation: {
      aria: "Cost anomaly correlated with a deployment",
      title: "Storage · Data team",
      badge: "Anomaly +38%",
      events: [
        { time: "14 Sep 10:02", label: "etl-v2.3 deployment", source: "Argo CD" },
        { time: "14 Sep 10:05", label: "12 × 500 GB volumes created", source: "Inventory" },
        { time: "15 Sep", label: "9 volumes detached, still billed", source: "Inventory" },
      ],
    },
  },
  sources: ["OVHcloud", "Scaleway", "3DS OUTSCALE", "OpenStack", "Kubernetes", "Prometheus", "VictoriaMetrics", "AWS · Azure · GCP (FOCUS)"],
  questions: [
    {
      kicker: "What does it cost?",
      title: "Real, allocated and forecast cost",
      text: "Public price lists imported daily, real invoices reconciled with the estimate, on-prem costs: every amount is traceable to its source and assigned to the right team.",
    },
    {
      kicker: "Is it well used?",
      title: "Cost matched against usage",
      text: "CPU, memory, storage and network set against what you pay for, from the VM down to the pod. Oversized, orphaned or always-on resources surface on their own.",
    },
    {
      kicker: "Why did it change?",
      title: "Every change explained",
      text: "A drift is automatically correlated with the deployments, inventory changes, autoscaling events and incidents in the same window, then explained with evidence.",
    },
  ],
  features: [
    {
      icon: "layers",
      title: "Allocation, showback and chargeback",
      text: "Business unit → team → service → environment hierarchy, rules by labels, projects or namespaces, shared costs split. Coverage rate always visible.",
    },
    {
      icon: "wand",
      title: "Ready-to-apply recommendations",
      text: "VM and Kubernetes rightsizing, orphaned resources, off-hours shutdown, flavor changes. Estimated savings, risk, evidence and a CLI command, manifest or Terraform snippet included.",
    },
    {
      icon: "pulse",
      title: "Correlated anomalies",
      text: "Seasonal detection for every series, correlation with GitLab, GitHub, Argo CD, Flux, Alertmanager, PagerDuty… and an explanation generated from the data.",
    },
    {
      icon: "target",
      title: "Budgets and forecasts",
      text: "Budgets at every level, alerts on actuals and on the end-of-period forecast, what-if simulations: adding nodes, changing flavors, moving clouds.",
    },
    {
      icon: "cube",
      title: "Kubernetes, down to the pod",
      text: "Node cost split hour by hour on max(requests, usage), idle cost made visible, control plane and shared costs included.",
    },
    {
      icon: "server",
      title: "On-prem and hybrid",
      text: "Amortised hardware, energy, licences and labour broken down into cost per vCPU, GB of RAM and GB of storage. A lightweight agent for unmonitored servers.",
    },
    {
      icon: "chat",
      title: "An AI assistant grounded in your data",
      text: "Ask questions in plain language. Every figure it quotes comes from the data, with sources; the assistant never has more permissions than you do.",
    },
    {
      icon: "report",
      title: "Monthly executive report",
      text: "Spend, trend, explained changes, savings achieved and three priority actions, in non-technical language. Sent as a PDF every month.",
    },
  ],
  personas: [
    {
      role: "DevOps and SRE",
      need: "Understand usage, rightsize, diagnose a drift.",
      points: ["Cost × usage from VM to pod", "Anomalies linked to deployments", "CLI, API and MCP server"],
    },
    {
      role: "CTOs and platform leads",
      need: "Allocate costs by team and steer the budget.",
      points: ["Allocation and shared costs", "Budgets and forecasts", "Configuration as code (Terraform)"],
    },
    {
      role: "Finance teams",
      need: "Know how much, why, and what to do.",
      points: ["Monthly executive report", "Exportable chargeback", "Estimated vs. billed gap tracked"],
    },
    {
      role: "MSPs and IT service providers",
      need: "Manage many customers and bill them back.",
      points: ["Multi-customer mode", "White-label reports", "Chargeback per customer"],
    },
  ],
  steps: [
    {
      n: "01",
      title: "Connect read-only",
      text: "Application credentials, service account or read-only API key: every connector documents the minimum permissions. Goal: first cloud connected in under 10 minutes.",
    },
    {
      n: "02",
      title: "See your costs",
      text: "Kairn imports up to 13 months of history when the source allows, prices it, allocates it and matches it with usage. Goal: first costs visible in under an hour.",
    },
    {
      n: "03",
      title: "Act and measure",
      text: "Accept a recommendation and apply the command provided: Kairn measures the savings actually achieved afterwards.",
    },
  ],
  sovereignty: [
    {
      icon: "globe",
      title: "Hosted in the EU",
      text: "SaaS run by a European hosting provider. No customer data leaves the EU, unless your organisation explicitly allows a call to a non-EU AI model.",
    },
    {
      icon: "server",
      title: "Full self-hosted edition",
      text: "The same product, deployed on your premises with a Helm chart. No mandatory outbound calls; SecNumCloud trajectory targeted.",
    },
    {
      icon: "chat",
      title: "Your choice of sovereign AI",
      text: "Anthropic, Mistral (sovereign option) or a local OpenAI-compatible model. Or no AI at all: your organisation decides.",
    },
    {
      icon: "lock",
      title: "Read-only, always",
      text: "Kairn never writes to your infrastructure. Credentials are envelope-encrypted (KMS or Vault) and never logged.",
    },
  ],
  security: [
    "Strict isolation between organisations (PostgreSQL Row-Level Security plus application checks, tested on every endpoint)",
    "RBAC (Owner, Admin, Finance, Engineer, Viewer) and per-team scopes",
    "OIDC and SAML SSO, MFA, SCIM provisioning",
    "Complete, exportable, append-only audit log",
    "Exact decimal amounts, traceable to the invoice line or price list",
    "GDPR: right to erasure, EU hosting",
  ],
  integrations: [
    { icon: "code", title: "REST API", text: "OpenAPI 3.1, scoped tokens, CSV and Parquet exports, signed webhooks." },
    { icon: "plug", title: "Terraform / OpenTofu", text: "Connectors, allocation and budgets managed as code." },
    { icon: "chat", title: "MCP server", text: "Your AI agents query Kairn with your permissions, nothing more." },
    { icon: "users", title: "Slack, Teams, Mattermost", text: "Alerts, email, PagerDuty and webhooks, with silences and deduplication." },
  ],
  plans: [
    {
      name: "Starter",
      target: "SMBs, one cloud",
      price: "≈ €99",
      unit: "/ month",
      features: ["Costs and usage", "Recommendations", "Budgets and alerts", "3 users"],
      highlight: false,
      contact: false,
    },
    {
      name: "Team",
      target: "Multi-cloud and Kubernetes",
      price: "≈ 1%",
      unit: "of tracked spend, from €490/month",
      features: ["Everything in Starter", "Allocation and chargeback", "Anomalies and AI assistant", "Monthly reports", "SSO"],
      highlight: true,
      contact: false,
    },
    {
      name: "Enterprise",
      target: "Large enterprises, public sector",
      price: "Custom",
      unit: "",
      features: ["Everything in Team", "Self-hosted edition", "SCIM and sovereign LLM", "SLA and dedicated support"],
      highlight: false,
      contact: true,
    },
    {
      name: "MSP",
      target: "MSPs and IT service providers",
      price: "Per customer",
      unit: "managed",
      features: ["Multi-customer", "White label", "Chargeback per customer"],
      highlight: false,
      contact: false,
    },
  ],
  faq: [
    {
      q: "Which clouds and platforms does Kairn support?",
      a: "OVHcloud, Scaleway, 3DS OUTSCALE, OpenStack (private or public), Kubernetes (managed or on-prem), Prometheus, VictoriaMetrics and Thanos. AWS, Azure and Google Cloud are covered through their billing exports in the FinOps FOCUS format, for hybrid environments.",
    },
    {
      q: "Does Kairn need write access to my infrastructure?",
      a: "No. Every connector is read-only and each type documents the minimum permissions to grant. Recommendations include the command to apply, but you are the one who runs it.",
    },
    {
      q: "Where is my data hosted?",
      a: "The SaaS service is hosted in the European Union. No data leaves the EU unless your organisation explicitly allows a non-European AI model. The self-hosted edition runs entirely on your premises.",
    },
    {
      q: "Do I need to install an agent?",
      a: "Rarely. Kairn uses what you already have: cloud APIs, Gnocchi, Prometheus, the Kubernetes API. A lightweight, unprivileged agent is available for servers with no monitoring at all.",
    },
    {
      q: "How are Kubernetes costs calculated?",
      a: "Each node's cost is split hour by hour among its pods based on the maximum of requests and usage (configurable). Capacity that is paid for but unused shows up as idle cost, and shared costs are split according to your rules.",
    },
    {
      q: "Can the AI assistant make up numbers?",
      a: "It only reaches data through typed tools, with your permissions, and every number in its answer is checked against those tools' results. Sources are cited; any unverified figure is flagged.",
    },
    {
      q: "How long does it take to get started?",
      a: "The goal is to connect a first cloud in under 10 minutes and see your first costs in under an hour, history included when the source allows.",
    },
  ],
  invoiceLines: [
    { label: "Public Cloud — Instances", amount: "€31,480.22" },
    { label: "Public Cloud — Block Storage", amount: "€9,912.40" },
    { label: "Object Storage", amount: "€4,715.38" },
    { label: "Public Cloud — Load Balancer", amount: "€2,106.00" },
  ],
  invoiceTotal: "€48,214.00",
  teamCosts: [
    { team: "Data", amount: "€14,950", share: 31, color: "bg-teal-400", note: "+28% · storage (etl-v2.3)" },
    { team: "Checkout", amount: "€10,600", share: 22, color: "bg-indigo-400", note: "stable" },
    { team: "Platform", amount: "€8,680", share: 18, color: "bg-sky-400", note: "incl. shared costs" },
    { team: "Search", amount: "€6,750", share: 14, color: "bg-violet-400", note: "−4%" },
    { team: "Mobile", amount: "€5,500", share: 11.4, color: "bg-emerald-400", note: "stable" },
    { team: "Unallocated", amount: "€1,734", share: 3.6, color: "bg-slate-500", note: "to assign" },
  ],
  drilldown: [
    { level: "Invoice", name: "OVHcloud · September", amount: "€48,214", share: 100, source: "Billing API", detail: "Invoice lines imported and reconciled with the estimate." },
    { level: "Project", name: "prod-eu", amount: "€29,870", share: 62, source: "OpenStack API", detail: "The project's VMs, volumes, IPs and load balancers, priced." },
    {
      level: "Kubernetes cluster",
      name: "prod-gra7 · 12 nodes",
      amount: "€18,420",
      share: 38,
      source: "Kubernetes API",
      detail: "Including €2,310 of capacity paid for but unused (idle cost).",
    },
    {
      level: "Node",
      name: "k8s-node-07 · VM 16 vCPU, 64 GiB",
      amount: "€486",
      share: 1,
      source: "providerID → VM",
      detail: "The node is linked to the VM hosting it, and therefore to its price.",
    },
    {
      level: "Pod",
      name: "payment-api-7f9c · namespace checkout",
      amount: "€121",
      share: 0.25,
      source: "Prometheus",
      detail: "Its share of the node on max(requests, usage): 4 vCPU reserved.",
    },
    {
      level: "Team",
      name: "Checkout · label team=checkout",
      amount: "€10,600",
      share: 22,
      source: "Allocation rule",
      detail: "All its pods, volumes and shared costs, ready to charge back.",
    },
  ],
};
