// Contenu éditorial du site vitrine, en français. Chaque affirmation correspond
// à une fonctionnalité réelle du produit (voir CLAUDE.md et docs/) : pas de
// chiffre ni de référence client inventés. Les montants des illustrations sont
// des données de démonstration (organisation fictive « Acme Retail »),
// cohérentes d'une section à l'autre : la facture de 48 214 € se retrouve dans
// la répartition par équipe, la descente jusqu'au pod et l'aperçu de l'interface.

import type { Content } from "./types";

export const fr: Content = {
  locale: "fr",
  htmlLang: "fr",
  numberLocale: "fr-FR",
  meta: {
    title: "Kairn — Observabilité des coûts pour clouds souverains, OpenStack et Kubernetes",
    description:
      "Kairn relie coûts, usage et déploiements sur OVHcloud, Scaleway, OUTSCALE, OpenStack et Kubernetes : combien vous dépensez, si c'est bien utilisé et pourquoi ça a bougé. FinOps souverain, hébergé dans l'UE ou en self-hosted.",
    keywords: [
      "FinOps",
      "FinOps souverain",
      "coûts cloud",
      "observabilité des coûts",
      "OVHcloud",
      "Scaleway",
      "OUTSCALE",
      "OpenStack",
      "Kubernetes",
      "showback",
      "chargeback",
      "rightsizing",
      "cloud souverain",
      "SecNumCloud",
    ],
    ogLocale: "fr_FR",
    ogAlt: "Kairn — le coût réel de votre cloud, enfin expliqué",
    ogTitle: "Le coût réel de votre cloud, enfin expliqué.",
    ogTagline: ["FinOps souverain", "Hébergé dans l'UE ou chez vous", "Lecture seule"],
  },
  ui: {
    skip: "Aller au contenu",
    home: "Kairn, accueil",
    mainNav: "Navigation principale",
    footerNav: "Pied de page",
    menu: "Menu",
    nav: [
      { href: "#cascade", label: "Comment ça marche" },
      { href: "#produit", label: "Produit" },
      { href: "#ia", label: "IA" },
      { href: "#souverainete", label: "Souveraineté" },
      { href: "#tarifs", label: "Tarifs" },
      { href: "#faq", label: "FAQ" },
    ],
    docs: "Documentation",
    login: "Se connecter",
    demo: "Demander une démo",
    demoSubject: "Demande de démo Kairn",
    otherLocale: { href: "/en/", hrefLang: "en", label: "EN", aria: "English version" },
    hero: {
      badge: "FinOps souverain · hébergé dans l'UE ou chez vous",
      titleA: "Le coût réel de votre cloud, ",
      titleB: "enfin expliqué.",
      text: "De la facture OVHcloud, Scaleway, OUTSCALE ou OpenStack jusqu'au pod Kubernetes : vous savez combien vous dépensez, si c'est bien utilisé — et pourquoi ça a bougé.",
      secondary: "Voir comment ça marche",
      checks: ["Connecteurs en lecture seule", "Premiers coûts en moins d'une heure", "Édition self-hosted complète"],
      scroll: "Faites défiler",
    },
    sourcesTitle: "Branché sur ce que vous utilisez déjà, sans nouvelle pile de supervision",
    problem: {
      eyebrow: "Le problème",
      titleA: "Votre facture vous dit combien.",
      titleB: "Jamais qui, ni pourquoi.",
      text: "Les outils FinOps du marché sont pensés pour AWS, Azure et GCP. Sur les clouds souverains, OpenStack et Kubernetes, les équipes finissent dans un tableur. Kairn transforme la même facture en réponses.",
    },
    cascade: {
      eyebrow: "Comment ça marche",
      titleA: "De la facture jusqu'au pod.",
      titleB: "Puis jusqu'à l'équipe qui paie.",
      text: "Kairn relie la facture, les projets cloud, les VM, les nodes Kubernetes et les pods qui tournent dessus. Chaque euro descend la chaîne, avec sa source.",
    },
    product: {
      eyebrow: "Produit",
      title: "Trois questions. Une réponse chiffrée pour chaque équipe.",
      text: "Chaque montant est traçable jusqu'à sa source : ligne de facture, grille tarifaire versionnée ou métrique.",
      bullets: [
        ["Grilles publiques versionnées et factures réelles", "Hiérarchie équipe → service → environnement", "Chargeback exportable en CSV ou par API"],
        ["Usage réel au 95ᵉ centile, sur fenêtre glissante", "Orphelins et environnements allumés la nuit", "Commande kubectl, OpenStack ou Terraform fournie"],
        ["Baseline saisonnière par série de coûts", "Déploiements, HPA, incidents et inventaire croisés", "Explication générée, preuves à l'appui"],
      ],
    },
    features: { eyebrow: "Tout le reste", title: "De la facture à l'action, sans tableur" },
    ai: {
      eyebrow: "Assistant IA",
      title: "Posez la question. Obtenez des chiffres vérifiés.",
      text: "L'assistant interroge vos données à travers des outils typés, avec exactement vos droits. Chaque nombre de sa réponse est contrôlé contre les résultats de ces outils, et les sources sont citées.",
      bullets: [
        "Anthropic, Mistral (option souveraine) ou modèle local — ou pas d'IA du tout",
        "Aucun appel hors UE sans l'accord explicite de votre organisation",
        "Rapport mensuel exécutif rédigé pour la direction, envoyé en PDF",
        "Serveur MCP : vos propres agents IA interrogent Kairn avec vos droits",
      ],
      aria: "Exemple de conversation avec l'assistant Kairn",
      question: "Pourquoi les coûts de l'équipe Data ont-ils augmenté ce mois-ci ?",
      answer: [
        ["L'équipe Data a dépensé ", { b: "14 950 €" }, " en septembre, soit ", { b: "+3 290 €" }, " (+28,2 %) par rapport à août."],
        [
          "La hausse vient surtout du stockage : ",
          { b: "+2 480 €" },
          " après le déploiement ",
          { code: "etl-v2.3" },
          " du 14, qui a créé 12 volumes dont 9 ne sont plus attachés.",
        ],
      ],
      action: ["Action suggérée : supprimer les 9 volumes orphelins (", { b: "−612 €/mois" }, "). Commande prête dans la recommandation."],
      sources: "Sources : coûts par équipe, événements Argo CD, inventaire des volumes.",
      caption: "Exemple illustratif, données de démonstration.",
    },
    personas: { eyebrow: "Pour qui", title: "Une seule source de vérité, de l'ingénieur à la direction financière" },
    steps: { eyebrow: "Mise en route", title: "Opérationnel en une journée, pas en un trimestre" },
    sovereignty: {
      eyebrow: "Souveraineté",
      titleA: "Vos données de coûts restent en Europe. ",
      titleB: "Ou chez vous.",
      text: "Vos coûts révèlent votre architecture, vos volumes et vos clients. Kairn est conçu pour que vous en gardiez la maîtrise.",
    },
    security: { eyebrow: "Sécurité", title: "Conçu pour les exigences des grands comptes et du secteur public" },
    integrations: { eyebrow: "Intégrations", title: "Dans vos outils et vos pipelines" },
    pricing: {
      eyebrow: "Tarifs",
      title: "Un prix aligné sur la valeur, pas sur le nombre de ressources",
      text: "Prix indicatifs hors taxes. Les limites de chaque plan sont appliquées par la plateforme.",
      highlight: "Le plus complet",
      contact: "Nous contacter",
      demo: "Demander une démo",
      planSr: "plan",
    },
    faqTitle: "Questions fréquentes",
    cta: {
      titleA: "Voyez vos propres coûts, ",
      titleB: "expliqués.",
      text: "Une démonstration de 30 minutes sur votre contexte : clouds, Kubernetes, organisation des équipes et contraintes de souveraineté.",
      docs: "Explorer la documentation",
    },
    footer: {
      tagline: "Observabilité des coûts pour les clouds souverains, OpenStack et Kubernetes.",
      product: "Produit",
      howItWorks: "Comment ça marche",
      features: "Fonctionnalités",
      assistant: "Assistant IA",
      pricing: "Tarifs",
      resources: "Ressources",
      connectors: "Connecteurs",
      securityLink: "Sécurité",
      contact: "Contact",
      rights: "Tous droits réservés.",
    },
  },
  mock: {
    aria: "Aperçu de l'interface Kairn avec des données de démonstration",
    windowTitle: "app.kairn · Acme Retail · Vue d'ensemble",
    sidebar: ["Vue d'ensemble", "Explorateur de coûts", "Coût × usage", "Allocation", "Recommandations", "Anomalies", "Budgets", "Assistant IA"],
    kpis: [
      { label: "Dépense du mois", value: "48 214 €", sub: "+6,2 %", tone: "warn" },
      { label: "Prévision fin de mois", value: "61 900 €", sub: "budget 64 000 €", tone: "muted" },
      { label: "Économies possibles", value: "7 420 €/mois", sub: "18 recommandations", tone: "good" },
      { label: "Coûts alloués", value: "96,4 %", sub: "objectif > 95 %", tone: "good" },
    ],
    chartTitle: "Coût journalier par fournisseur",
    chartRange: "20 derniers jours",
    legend: ["OVHcloud", "Kubernetes", "Stockage"],
    anomalyTitle: "Anomalie détectée",
    anomalyHeadline: "Stockage de l'équipe Data : +38 % depuis le 14",
    anomalyText: ["Coïncide avec le déploiement ", { code: "etl-v2.3" }, " (Argo CD) : 12 volumes de 500 Go créés, dont 9 non attachés."],
    recoLabel: "Recommandation",
    recoText: "Supprimer 9 volumes orphelins",
    recoSaving: "−612 €/mois",
    chipAccepted: "Recommandation acceptée",
    chipCorrelated: "Corrélé automatiquement",
    caption: "Aperçu de l'interface — données de démonstration.",
  },
  visuals: {
    demoNote: "Illustration — données de démonstration.",
    invoiceTitle: "Ce que dit votre facture",
    invoiceBadge: "PDF fournisseur",
    invoiceTotalLabel: "Total HT",
    invoiceQuestion: "Qui a consommé ces 31 480 € d'instances ? Pourquoi +6 % ce mois-ci ? La facture ne le dit pas.",
    kairnTitle: "Ce que dit Kairn",
    kairnBadge: "96,4 % alloué",
    kairnHighlight: [{ b: "Équipe Data +28 %" }, " : 12 volumes créés par le déploiement ", { code: "etl-v2.3" }, ", dont 9 orphelins."],
    drilldownAria: "Descente d'un coût, de la facture jusqu'au pod puis à l'équipe",
    allocationAria: "Répartition de la dépense par équipe",
    allocationTitle: "Dépense de septembre",
    allocationCoverage: "Couverture 96,4 %",
    allocationTotal: "48 214 €",
    rightsizing: {
      aria: "Exemple de recommandation de dimensionnement",
      replicas: "3 réplicas",
      badge: "Surdimensionné ×3",
      cpu: "CPU (P95, 30 jours)",
      memory: "Mémoire (P95, 30 jours)",
      usedOf: "utilisés sur",
      reserved: "réservés",
      memoryUnit: "Gio",
      comment: "# Commande prête à appliquer",
      saving: "−227 €/mois estimés",
      risk: "Risque faible",
      measured: "Économie mesurée après application",
    },
    correlation: {
      aria: "Anomalie de coût corrélée à un déploiement",
      title: "Stockage · équipe Data",
      badge: "Anomalie +38 %",
      events: [
        { time: "14 sept. 10:02", label: "Déploiement etl-v2.3", source: "Argo CD" },
        { time: "14 sept. 10:05", label: "12 volumes de 500 Go créés", source: "Inventaire" },
        { time: "15 sept.", label: "9 volumes détachés, toujours facturés", source: "Inventaire" },
      ],
    },
  },
  sources: ["OVHcloud", "Scaleway", "3DS OUTSCALE", "OpenStack", "Kubernetes", "Prometheus", "VictoriaMetrics", "AWS · Azure · GCP (FOCUS)"],
  questions: [
    {
      kicker: "Combien ça coûte ?",
      title: "Le coût réel, alloué et prévu",
      text: "Grilles publiques importées chaque jour, factures réelles rapprochées de l'estimation, coûts on-prem : chaque montant est traçable jusqu'à sa source et attribué à la bonne équipe.",
    },
    {
      kicker: "Est-ce bien utilisé ?",
      title: "Le coût croisé avec l'usage",
      text: "CPU, mémoire, stockage et réseau rapprochés de ce que vous payez, de la VM au pod. Les ressources surdimensionnées, orphelines ou allumées la nuit ressortent d'elles-mêmes.",
    },
    {
      kicker: "Pourquoi ça a bougé ?",
      title: "Les variations expliquées",
      text: "Une dérive est automatiquement corrélée aux déploiements, changements d'inventaire, événements d'autoscaling et incidents de la même fenêtre, puis expliquée preuves à l'appui.",
    },
  ],
  features: [
    {
      icon: "layers",
      title: "Allocation, showback et chargeback",
      text: "Hiérarchie business unit → équipe → service → environnement, règles par labels, projets ou namespaces, coûts partagés répartis. Taux de couverture affiché.",
    },
    {
      icon: "wand",
      title: "Recommandations prêtes à appliquer",
      text: "Rightsizing VM et Kubernetes, orphelins, arrêts hors heures ouvrées, changement de gamme. Économie estimée, risque, preuves et commande CLI, manifeste ou Terraform fournis.",
    },
    {
      icon: "pulse",
      title: "Anomalies corrélées",
      text: "Détection saisonnière par série, corrélation avec GitLab, GitHub, Argo CD, Flux, Alertmanager, PagerDuty… et explication générée à partir des données.",
    },
    {
      icon: "target",
      title: "Budgets et prévisions",
      text: "Budgets à tous les niveaux, alertes sur le réel et sur la prévision de fin de période, simulations what-if : ajout de nodes, changement de gamme, migration de cloud.",
    },
    {
      icon: "cube",
      title: "Kubernetes, au pod près",
      text: "Coût des nodes réparti heure par heure selon max(requests, usage), coût idle rendu visible, plan de contrôle et coûts partagés intégrés.",
    },
    {
      icon: "server",
      title: "On-prem et hybride",
      text: "Matériel amorti, énergie, licences et main-d'œuvre ventilés en coût par vCPU, Go de RAM et Go de stockage. Un agent léger pour les serveurs sans supervision.",
    },
    {
      icon: "chat",
      title: "Assistant IA ancré dans vos données",
      text: "Posez vos questions en langage naturel. Chaque chiffre cité provient des données, avec ses sources ; l'assistant n'a jamais plus de droits que vous.",
    },
    {
      icon: "report",
      title: "Rapport mensuel exécutif",
      text: "Dépense, évolution, variations expliquées, économies réalisées et trois actions prioritaires, en langage non technique. Envoyé en PDF chaque mois.",
    },
  ],
  personas: [
    {
      role: "DevOps et SRE",
      need: "Comprendre l'usage, dimensionner, diagnostiquer une dérive.",
      points: ["Coût × usage de la VM au pod", "Anomalies reliées aux déploiements", "CLI, API et serveur MCP"],
    },
    {
      role: "CTO et responsables plateforme",
      need: "Allouer les coûts par équipe et piloter le budget.",
      points: ["Allocation et coûts partagés", "Budgets et prévisions", "Configuration as code (Terraform)"],
    },
    {
      role: "Directions financières",
      need: "Savoir combien, pourquoi, et quoi faire.",
      points: ["Rapport mensuel exécutif", "Chargeback exportable", "Écart estimé / facturé suivi"],
    },
    {
      role: "ESN et infogéreurs",
      need: "Gérer plusieurs clients et refacturer.",
      points: ["Mode multi-clients", "Rapports en marque blanche", "Chargeback par client"],
    },
  ],
  steps: [
    {
      n: "01",
      title: "Connectez en lecture seule",
      text: "Identifiants d'application, compte de service ou clé API en lecture seule : chaque connecteur documente les permissions minimales. Objectif : premier cloud connecté en moins de 10 minutes.",
    },
    {
      n: "02",
      title: "Visualisez vos coûts",
      text: "Kairn importe jusqu'à 13 mois d'historique quand la source le permet, tarifie, alloue et croise avec l'usage. Objectif : premiers coûts visibles en moins d'une heure.",
    },
    {
      n: "03",
      title: "Agissez et mesurez",
      text: "Acceptez une recommandation, appliquez la commande fournie : Kairn mesure l'économie réellement obtenue après application.",
    },
  ],
  sovereignty: [
    {
      icon: "globe",
      title: "Hébergé dans l'UE",
      text: "SaaS opéré chez un hébergeur européen. Aucune donnée client hors UE, sauf appel à un modèle d'IA explicitement autorisé par votre organisation.",
    },
    {
      icon: "server",
      title: "Édition self-hosted complète",
      text: "Le même produit, déployé chez vous par chart Helm. Aucun appel sortant obligatoire ; trajectoire SecNumCloud visée.",
    },
    {
      icon: "chat",
      title: "IA souveraine au choix",
      text: "Anthropic, Mistral (option souveraine) ou modèle local compatible OpenAI. Ou pas d'IA du tout : c'est votre organisation qui décide.",
    },
    {
      icon: "lock",
      title: "Lecture seule, toujours",
      text: "Kairn n'écrit jamais sur votre infrastructure. Credentials chiffrés par enveloppe (KMS ou Vault), jamais journalisés.",
    },
  ],
  security: [
    "Isolation stricte entre organisations (Row-Level Security PostgreSQL + contrôle applicatif, testée sur chaque endpoint)",
    "RBAC (Owner, Admin, Finance, Engineer, Viewer) et périmètres par équipe",
    "SSO OIDC et SAML, MFA, provisionnement SCIM",
    "Journal d'audit complet, exportable et en ajout seul",
    "Montants en décimal exact, traçables jusqu'à la ligne de facture ou la grille tarifaire",
    "RGPD : droit à l'effacement, hébergement UE",
  ],
  integrations: [
    { icon: "code", title: "API REST", text: "OpenAPI 3.1, jetons scoppés, exports CSV et Parquet, webhooks signés." },
    { icon: "plug", title: "Terraform / OpenTofu", text: "Connecteurs, allocation et budgets gérés as code." },
    { icon: "chat", title: "Serveur MCP", text: "Vos agents IA interrogent Kairn avec vos droits, rien de plus." },
    { icon: "users", title: "Slack, Teams, Mattermost", text: "Alertes, e-mail, PagerDuty et webhooks, avec silences et déduplication." },
  ],
  plans: [
    {
      name: "Starter",
      target: "PME, un cloud",
      price: "≈ 99 €",
      unit: "/ mois",
      features: ["Coûts et usage", "Recommandations", "Budgets et alertes", "3 utilisateurs"],
      highlight: false,
      contact: false,
    },
    {
      name: "Team",
      target: "Multi-cloud et Kubernetes",
      price: "≈ 1 %",
      unit: "de la dépense suivie, dès 490 €/mois",
      features: ["Tout Starter", "Allocation et chargeback", "Anomalies et assistant IA", "Rapports mensuels", "SSO"],
      highlight: true,
      contact: false,
    },
    {
      name: "Enterprise",
      target: "Grands comptes, secteur public",
      price: "Sur devis",
      unit: "",
      features: ["Tout Team", "Édition self-hosted", "SCIM et LLM souverain", "SLA et support dédié"],
      highlight: false,
      contact: true,
    },
    {
      name: "MSP",
      target: "ESN et infogéreurs",
      price: "Par client",
      unit: "géré",
      features: ["Multi-clients", "Marque blanche", "Chargeback par client"],
      highlight: false,
      contact: false,
    },
  ],
  faq: [
    {
      q: "Quels clouds et plateformes Kairn prend-il en charge ?",
      a: "OVHcloud, Scaleway, 3DS OUTSCALE, OpenStack (privé ou public), Kubernetes (managé ou on-prem), Prometheus, VictoriaMetrics et Thanos. AWS, Azure et Google Cloud sont couverts via leurs exports de facturation au format FinOps FOCUS, pour les environnements hybrides.",
    },
    {
      q: "Kairn a-t-il besoin d'accès en écriture à mon infrastructure ?",
      a: "Non. Tous les connecteurs sont en lecture seule et chaque type documente les permissions minimales à accorder. Les recommandations fournissent la commande à appliquer, mais c'est vous qui l'exécutez.",
    },
    {
      q: "Où sont hébergées mes données ?",
      a: "Le service SaaS est hébergé dans l'Union européenne. Aucune donnée ne quitte l'UE, sauf si votre organisation autorise explicitement un modèle d'IA non européen. L'édition self-hosted s'installe entièrement chez vous.",
    },
    {
      q: "Faut-il installer un agent ?",
      a: "Rarement. Kairn consomme ce que vous avez déjà : API des clouds, Gnocchi, Prometheus, API Kubernetes. Un agent léger, sans privilège, existe pour les serveurs sans aucune supervision.",
    },
    {
      q: "Comment les coûts Kubernetes sont-ils calculés ?",
      a: "Le coût de chaque node est réparti heure par heure entre ses pods selon le maximum des requests et de l'usage (méthode configurable). La capacité payée mais inutilisée apparaît comme coût idle, et les coûts partagés sont répartis selon vos règles.",
    },
    {
      q: "L'assistant IA peut-il inventer des chiffres ?",
      a: "Il n'accède aux données qu'au travers d'outils typés, avec vos droits, et chaque nombre de sa réponse est vérifié contre les résultats de ces outils. Les sources sont citées ; un chiffre non vérifié est signalé.",
    },
    {
      q: "Combien de temps pour démarrer ?",
      a: "L'objectif est de connecter un premier cloud en moins de 10 minutes et de voir ses premiers coûts en moins d'une heure, historique compris quand la source le permet.",
    },
  ],
  invoiceLines: [
    { label: "Public Cloud — Instances", amount: "31 480,22 €" },
    { label: "Public Cloud — Block Storage", amount: "9 912,40 €" },
    { label: "Object Storage", amount: "4 715,38 €" },
    { label: "Public Cloud — Load Balancer", amount: "2 106,00 €" },
  ],
  invoiceTotal: "48 214,00 €",
  teamCosts: [
    { team: "Data", amount: "14 950 €", share: 31, color: "bg-teal-400", note: "+28 % · stockage (etl-v2.3)" },
    { team: "Checkout", amount: "10 600 €", share: 22, color: "bg-indigo-400", note: "stable" },
    { team: "Plateforme", amount: "8 680 €", share: 18, color: "bg-sky-400", note: "coûts partagés inclus" },
    { team: "Search", amount: "6 750 €", share: 14, color: "bg-violet-400", note: "−4 %" },
    { team: "Mobile", amount: "5 500 €", share: 11.4, color: "bg-emerald-400", note: "stable" },
    { team: "Non alloué", amount: "1 734 €", share: 3.6, color: "bg-slate-500", note: "à attribuer" },
  ],
  drilldown: [
    { level: "Facture", name: "OVHcloud · septembre", amount: "48 214 €", share: 100, source: "API de facturation", detail: "Lignes de facture importées, rapprochées de l'estimation." },
    { level: "Projet", name: "prod-eu", amount: "29 870 €", share: 62, source: "API OpenStack", detail: "VM, volumes, IP et load balancers du projet, tarifés." },
    {
      level: "Cluster Kubernetes",
      name: "prod-gra7 · 12 nodes",
      amount: "18 420 €",
      share: 38,
      source: "API Kubernetes",
      detail: "Dont 2 310 € de capacité payée mais inutilisée (coût idle).",
    },
    {
      level: "Node",
      name: "k8s-node-07 · VM 16 vCPU, 64 Gio",
      amount: "486 €",
      share: 1,
      source: "providerID → VM",
      detail: "Le node est rattaché à la VM qui l'héberge, donc à son prix.",
    },
    {
      level: "Pod",
      name: "payment-api-7f9c · namespace checkout",
      amount: "121 €",
      share: 0.25,
      source: "Prometheus",
      detail: "Part du node selon max(requests, usage) : 4 vCPU réservés.",
    },
    {
      level: "Équipe",
      name: "Checkout · label team=checkout",
      amount: "10 600 €",
      share: 22,
      source: "Règle d'allocation",
      detail: "Tous ses pods, volumes et coûts partagés, refacturables.",
    },
  ],
};
